[package]
name = "noife"
version = "0.1.0"
edition = "2021"
default-run = "nustup"

[[bin]]
name = "nustup"

[[bin]]
name = "nargo"

[[bin]]
name = "nalyzer"

[lib]
name = "playground_common"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.87"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
